.PHONY: gen-api gen-types gen-mocks sync-env check-deps update-deps

gen-api:
	@echo "generating API client"

gen-types: gen-api
	@echo "generating types"

gen-mocks: gen-types
	@echo "generating mocks"

sync-env:
	@echo "syncing env files"

check-deps:
	@echo "checking dependencies"

update-deps: check-deps
	@echo "updating dependencies"
