.PHONY: init plan apply destroy validate fmt state-list import

init:
	@echo "terraform init"

plan: init
	@echo "terraform plan"

apply: plan
	@echo "terraform apply"

destroy: init
	@echo "terraform destroy"

validate: init
	@echo "terraform validate"

fmt:
	@echo "terraform fmt"

state-list: init
	@echo "terraform state list"

import: init
	@echo "terraform import"
