.PHONY: up down restart build prune logs ps

up:
	@echo "docker compose up"

down:
	@echo "docker compose down"

restart: down up
	@echo "restarted"

build:
	@echo "docker compose build"

prune:
	@echo "pruning docker"

logs:
	@echo "showing logs"

ps:
	@echo "showing containers"
