---
name: CI

env:
  CI: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    needs:
      - build
    runs-on: ${{ matrix.os }}
    name: Lint (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout codes
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Vite Plus
        uses: voidzero-dev/setup-vp@b5d848f5a62488f3d3d920f8aa6ac318a60c5f07 # v1.0.0
        with:
          node-version: 22
          cache: true

      - name: Install dependencies
        run: vp install

      - name: Download binding artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: binding-${{ matrix.os }}
          path: binding

      - name: Check strictly codes
        run: vp run check

  test:
    needs:
      - build
    runs-on: ${{ matrix.os }}
    name: Test (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout codes
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Vite Plus
        uses: voidzero-dev/setup-vp@b5d848f5a62488f3d3d920f8aa6ac318a60c5f07 # v1.0.0
        with:
          node-version: 22
          cache: true

      - name: Install dependencies
        run: vp install

      - name: Download binding artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: binding-${{ matrix.os }}
          path: binding

      - name: Testing
        run: vp run test

  build:
    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout codes
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Vite Plus
        uses: voidzero-dev/setup-vp@b5d848f5a62488f3d3d920f8aa6ac318a60c5f07 # v1.0.0
        with:
          node-version: 22
          cache: true

      - name: Install dependencies
        run: vp install

      - name: Building
        run: vp run build

      - name: Upload binding artifact
        uses: actions/upload-artifact@ea165f8d65b6db9a6b7a0d7c2b898defc3680da4 # v4.6.2
        with:
          name: binding-${{ matrix.os }}
          path: binding/
