---
name: CI

env:
  CI: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    needs:
      - build
    runs-on: ${{ matrix.os }}
    name: Lint (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout codes
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Setup Vite Plus
        uses: voidzero-dev/setup-vp@1b32467adbe183473499fd9d5d372c3ed9641754 # v1.18.0
        with:
          node-version: 22
          cache: true
          run-install: false

      - name: Install dependencies
        run: vp install --no-frozen-lockfile

      - name: Download binding artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: binding-${{ matrix.os }}
          path: binding

      - name: Check strictly codes
        run: vp run check

  test:
    needs:
      - build
    runs-on: ${{ matrix.os }}
    name: Test (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout codes
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Setup Vite Plus
        uses: voidzero-dev/setup-vp@1b32467adbe183473499fd9d5d372c3ed9641754 # v1.18.0
        with:
          node-version: 22
          cache: true
          run-install: false

      - name: Install dependencies
        run: vp install --no-frozen-lockfile

      - name: Download binding artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: binding-${{ matrix.os }}
          path: binding

      - name: Testing
        run: vp run test

  build:
    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout codes
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Setup Vite Plus
        uses: voidzero-dev/setup-vp@1b32467adbe183473499fd9d5d372c3ed9641754 # v1.18.0
        with:
          node-version: 22
          cache: true
          run-install: false

      - name: Install dependencies
        run: vp install --no-frozen-lockfile

      - name: Building
        run: vp run build

      - name: Upload binding artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: binding-${{ matrix.os }}
          path: binding/
